apiVersion: v1
kind: Service
metadata:
    name: "aksqastg001-2427"
    labels:
        app: "aksqastg001-2427"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksqastg001-2427"